package br.com.raffa.websocket.providers;


import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test(){
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtoemRJU1NHTEtENXl3TUQwajd4QiJ9.eyJnaXZlbl9uYW1lIjoiUmFmYWVsIiwiZmFtaWx5X25hbWUiOiJDdW5oYSBSaWJlaXJvIiwibmlja25hbWUiOiJyYWZmYWVsbC5wbGF5IiwibmFtZSI6IlJhZmFlbCBDdW5oYSBSaWJlaXJvIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xPS1NLZFlOMFA4RndnNDJrb2l6bWJPWlV3RmF3UnVMdElfM0IzaGppdD1zOTYtYyIsImxvY2FsZSI6InB0LUJSIiwidXBkYXRlZF9hdCI6IjIwMjMtMTEtMjdUMjI6MzE6MjMuMjkzWiIsImVtYWlsIjoicmFmZmFlbGwucGxheUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtcmFmZmFlbGwudXMuYXV0aDAuY29tLyIsImF1ZCI6Imc5bkFaOFFxdm1lcTdxZVlISWpPRlJ4Y0xCOHgyck44IiwiaWF0IjoxNzAxMTI0MjkxLCJleHAiOjE3MDExNjAyOTEsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTAwODQ1NzU4MzA3NDE3MjU1ODQ2Iiwic2lkIjoiZHo2VGVfMFVfcUtFY09idTZtdjdHN3pKRlpqZ0ZtQjAiLCJub25jZSI6IlQwOWhjM2RoVms1UGVUZFVOVFpOUVZKaFprWTJVa0UzVUhFMVIwVjVRWGx3Y1Vwc2IwTmFWbU5VU0E9PSJ9.cHjA3r7CSmAMQWuVuUJ9dkfvAUUBnLaaYbYe24VuXY6jE8bOK7K_BbHy0H6hBvH7z6E_EOUZNvhlGz-q2NMdgzqHHzEi8gt9cV_hvbInN0suFlgl4XSD3pBOWOTgAPRPXmVpllrXr8Mwp2ki62c4hB_gpkMZ-2JAez-g8oDMun0BSql4TqshruHm_KY_0I-Ycj_FjWho7zf54yEnR09OxrESFv67GQ9H_GQABBtEUR5tVlfhgqlAnFgiA46vF6y-DiF-qPfeZ_9XL2LeEOCJYR-XfJ10rJ1h6iEDyuJxrj3S-NNwFaV8yAnHxAcJtCO_Jnb1l0W0bKsvSwYDk7CtLQ");
        System.out.println(decoded);
    }

}
